In [1]:

from my_trader import *

C:\ProgramData\Anaconda2\lib\site-packages\fix_yahoo_finance\__init__.py:43: DeprecationWarning:
    Auto-overriding of pandas_datareader's get_data_yahoo() is deprecated and no longer available.
    Use pdr_override() to explicitly override it.
  DeprecationWarning)

In [24]:
robinhood = get_robinhood()

In [4]:
get_price_data(["VIXY"],method="day",start_date=datetime.now()-timedelta(days=210),end_date=datetime.now()-timedelta(days=0))

Finished VIXY

,Ticker,TimeStamp,Open,High,Low,Close,Adj Close,Volume,Return
0,VIXY,2017-07-28,38.000000,38.509998,37.439999,37.540001,37.540001,1536500.0,NaN
1,VIXY,2017-07-31,37.040001,37.730000,36.959999,37.279999,37.279999,937100.0,-0.006974
2,VIXY,2017-08-01,36.820000,37.099998,36.619999,36.799999,36.799999,960200.0,-0.013043
3,VIXY,2017-08-02,36.580002,37.700001,36.580002,37.000000,37.000000,1381000.0,0.005405
4,VIXY,2017-08-03,37.070000,37.599998,37.009998,37.470001,37.470001,1109900.0,0.012543
5,VIXY,2017-08-04,37.270000,37.430000,36.820000,37.310001,37.310001,748800.0,-0.004288
6,VIXY,2017-08-07,37.180000,37.320000,36.830002,36.849998,36.849998,441700.0,-0.012483
7,VIXY,2017-08-08,36.900002,38.380001,36.340000,37.900002,37.900002,1618700.0,0.027705
8,VIXY,2017-08-09,38.919998,39.990002,38.099998,38.889999,38.889999,2409000.0,0.025456
9,VIXY,2017-08-10,39.910000,44.360001,39.900002,44.189999,44.189999,6362100.0,0.119937
10,VIXY,2017-08-11,44.549999,46.810001,43.119999,45.500000,45.500000,4574000.0,0.028791
11,VIXY,2017-08-14,41.959999,42.000000,39.470001,39.570000,39.570000,2188000.0,-0.149861
12,VIXY,2017-08-15,38.480000,40.009998,38.480000,39.290001,39.290001,1510900.0,-0.007126
13,VIXY,2017-08-16,39.279999,39.580002,38.689999,39.060001,39.060001,2300100.0,-0.005888
14,VIXY,2017-08-17,40.040001,45.560001,39.470001,45.529999,45.529999,5242300.0,0.142104
15,VIXY,2017-08-18,44.110001,45.639999,42.020000,44.189999,44.189999,3176700.0,-0.030324
16,VIXY,2017-08-21,43.849998,44.820000,42.330002,42.439999,42.439999,1755300.0,-0.041235
17,VIXY,2017-08-22,41.180000,41.230000,39.169998,39.320000,39.320000,2008500.0,-0.079349
18,VIXY,2017-08-23,40.959999,41.240002,39.369999,39.660000,39.660000,1690700.0,0.008573
19,VIXY,2017-08-24,39.459999,41.619999,39.250000,40.759998,40.759998,1185200.0,0.026987
20,VIXY,2017-08-25,40.029999,40.450001,39.439999,39.630001,39.630001,1470200.0,-0.028514
21,VIXY,2017-08-28,39.169998,40.090000,39.070000,39.279999,39.279999,1337500.0,-0.008910
22,VIXY,2017-08-29,42.139999,42.380001,39.630001,39.750000,39.750000,2328600.0,0.011824
23,VIXY,2017-08-30,39.700001,40.040001,39.290001,39.540001,39.540001,1388300.0,-0.005311
24,VIXY,2017-08-31,39.290001,39.360001,38.369999,38.459999,38.459999,1676600.0,-0.028081
25,VIXY,2017-09-01,38.119999,38.470001,37.980000,38.349998,38.349998,1188500.0,-0.002868
26,VIXY,2017-09-05,39.759998,42.150002,38.990002,40.439999,40.439999,2660700.0,0.051682
27,VIXY,2017-09-06,39.610001,40.560001,39.400002,39.500000,39.500000,1038000.0,-0.023797
28,VIXY,2017-09-07,39.500000,40.119999,39.020000,39.299999,39.299999,1024000.0,-0.005089
29,VIXY,2017-09-08,39.889999,40.560001,39.689999,40.259998,40.259998,1056300.0,0.023845
...,...,...,...,...,...,...,...,...,...
115,VIXY,2018-01-11,21.360001,21.500000,21.240000,21.430000,21.430000,666500.0,-0.006066
116,VIXY,2018-01-12,21.340000,21.520000,21.280001,21.440001,21.440001,909600.0,0.000466
117,VIXY,2018-01-16,21.580000,22.990000,21.530001,22.760000,22.760000,2694400.0,0.057996
118,VIXY,2018-01-17,22.500000,23.139999,21.780001,22.230000,22.230000,2647000.0,-0.023842
119,VIXY,2018-01-18,22.620001,23.080000,22.000000,22.340000,22.340000,2669100.0,0.004924
120,VIXY,2018-01-19,22.280001,22.709999,22.180000,22.260000,22.260000,1443600.0,-0.003594
121,VIXY,2018-01-22,22.420000,22.420000,21.600000,21.790001,21.790001,1200100.0,-0.021569
122,VIXY,2018-01-23,22.020000,22.379999,21.840000,22.139999,22.139999,1631900.0,0.015808
123,VIXY,2018-01-24,22.270000,23.309999,22.250000,22.719999,22.719999,2389600.0,0.025528
124,VIXY,2018-01-25,22.600000,23.480000,22.580000,23.100000,23.100000,1778900.0,0.016450
125,VIXY,2018-01-26,22.879999,23.240000,22.820000,22.930000,22.930000,1113000.0,-0.007414
126,VIXY,2018-01-29,23.490000,24.650000,22.549999,24.600000,24.600000,1593900.0,0.067886
127,VIXY,2018-01-30,25.450001,26.530001,25.000000,25.379999,25.379999,4294600.0,0.030733
128,VIXY,2018-01-31,24.830000,25.600000,24.480000,24.799999,24.799999,2325300.0,-0.023387
129,VIXY,2018-02-01,25.000000,25.240000,23.250000,24.040001,24.040001,3283500.0,-0.031614
130,VIXY,2018-02-02,24.770000,27.799999,24.770000,27.309999,27.309999,7679900.0,0.119736
131,VIXY,2018-02-05,28.690001,36.959999,26.750000,36.660000,36.660000,10085600.0,0.255046
132,VIXY,2018-02-06,45.080002,45.860001,35.000000,35.470001,35.470001,10172200.0,-0.033549
133,VIXY,2018-02-07,37.240002,37.599998,33.689999,36.869999,36.869999,7595400.0,0.037971
134,VIXY,2018-02-08,37.230000,45.860001,37.080002,45.770000,45.770000,9097200.0,0.194451
135,VIXY,2018-02-09,41.910000,46.840000,40.299999,41.410000,41.410000,3579300.0,-0.105289
136,VIXY,2018-02-12,39.990002,42.000000,39.009998,39.680000,39.680000,3223200.0,-0.043599
137,VIXY,2018-02-13,40.720001,41.230000,39.320000,39.720001,39.720001,3723600.0,0.001007
138,VIXY,2018-02-14,39.490002,39.700001,34.980000,35.080002,35.080002,4533100.0,-0.132269
139,VIXY,2018-02-15,33.950001,35.799999,33.820000,34.400002,34.400002,2023100.0,-0.019767
140,VIXY,2018-02-16,35.419998,35.560001,33.459999,34.880001,34.880001,4038300.0,0.013761
141,VIXY,2018-02-20,36.110001,37.310001,35.410000,36.389999,36.389999,3059800.0,0.041495
142,VIXY,2018-02-21,35.910000,37.049999,33.950001,36.869999,36.869999,3232400.0,0.013019
143,VIXY,2018-02-22,35.869999,37.040001,35.310001,36.240002,36.240002,2440200.0,-0.017384
144,VIXY,2018-02-23,35.410000,35.639999,34.130001,34.209999,34.209999,1532980.0,-0.059339

In [107]:
tickers, quantity = robinhood.get_my_positions()

UVXY 10.0000
ZNGA 1.0000
WCN 1.0000
AGFS 1.0000
AZN 1.0000
TAHO 1.0000
RRGB 1.0000
SPY 5.0000
IEP 1.0000
ESRX 4.0000
AIMC 2.0000
OSG 1.0000
ROYT 2.0000

In [37]:
temp = da.DataReader(tickers[0],"yahoo",datetime.now()-timedelta(days=90),datetime.now())
data = pd.DataFrame(index=temp.index)
temp = temp.rename(columns={"Adj Close":str(tickers[0]) + "_Close"})
temp = temp.rename(columns={"High":str(tickers[0]) + "_High"})
temp = temp.rename(columns={"Low":str(tickers[0]) + "_Low"})
data = pd.concat([data,temp[[str(tickers[0]) + "_Close",str(tickers[0]) + "_High",str(tickers[0]) + "_Low"]]], axis=1)
for i in tickers[1:]:
    temp = da.DataReader(i,"yahoo",datetime.now()-timedelta(days=90),datetime.now())
    temp = temp.rename(columns={"Adj Close":str(i) + "_Close"})
    temp = temp.rename(columns={"High":str(i) + "_High"})
    temp = temp.rename(columns={"Low":str(i) + "_Low"})
    data = pd.concat([data,temp[[str(i) + "_Close",str(i) + "_High",str(i) + "_Low"]]], axis=1)
data_weighted = pd.DataFrame(index = data.index)
for i, j in zip(data.columns,range(len(data.columns))):
    j = j / 3
    data_weighted = pd.concat([data_weighted,data[i] * quantity[j]],axis=1)

In [14]:
result = get_minute_data(["SPY"])

NameError: name 'get_minute_data' is not defined

In [7]:
def get_ondemand_data_test(sym, interval = 1,freq = 'minutes' ,start_date=(datetime.now()-timedelta(days=10))\
                    ,end_date=datetime.now()):

    '''Function to Retrieve <= 3 months of minute data for SP500 components'''
    api_key = 'b59b144a62e058b6c4e265c049dc679f'
    start_date=start_date.strftime("%Y%m%d%H%M%S")
    end_date=end_date.strftime("%Y%m%d%H%M%S")
    # This is the required format for datetimes to access the API

    api_url = 'http://marketdata.websol.barchart.com/getHistory.csv?' + \
                            'key={}&symbol={}&type={}&startDate={}&endDate={}&interval={}'\
                             .format(api_key, sym, freq, start_date,end_date,interval)

    csvfile = pd.read_csv(api_url)
    csvfile.set_index('timestamp', inplace=True)
            
    return csvfile

In [37]:
interval = 100

data = get_ondemand_data("SPY",start_date=datetime(2018,1,12),interval = interval )

In [40]:
data

,symbol,tradingDay,open,high,low,close,volume
timestamp,,,,,,,
2018-01-12 13:20:00,SPY,2018-01-12,276.4200,277.0300,276.2700,277.0300,4766441
2018-01-12 15:00:00,SPY,2018-01-12,277.0250,277.8100,276.8290,277.4700,13592889
2018-01-12 16:40:00,SPY,2018-01-12,277.4800,277.7200,277.3600,277.5500,7715507
2018-01-12 18:20:00,SPY,2018-01-12,277.5650,277.9200,277.5000,277.7550,11116204
2018-01-12 20:00:00,SPY,2018-01-12,277.7550,278.1100,277.3900,277.9100,18848219
2018-01-16 13:20:00,SPY,2018-01-16,279.3500,280.0900,279.2800,279.9900,7296399
2018-01-16 15:00:00,SPY,2018-01-16,280.0000,280.0100,278.3350,278.9900,16637502
2018-01-16 16:40:00,SPY,2018-01-16,278.9800,278.9800,278.1500,278.4500,9017182
2018-01-16 18:20:00,SPY,2018-01-16,278.4500,278.4600,276.1800,276.7600,18160890
2018-01-16 20:00:00,SPY,2018-01-16,276.7700,277.5900,276.7600,277.1200,19765145
2018-01-17 13:20:00,SPY,2018-01-17,278.0300,278.0400,277.1900,277.2800,6546203
2018-01-17 15:00:00,SPY,2018-01-17,277.2800,278.4800,277.2725,278.2900,12969579
2018-01-17 16:40:00,SPY,2018-01-17,278.2900,279.1950,278.2500,278.9338,8344963
2018-01-17 18:20:00,SPY,2018-01-17,278.9400,279.8700,278.9300,279.8100,13794416
2018-01-17 20:00:00,SPY,2018-01-17,279.8100,280.0500,279.3300,279.6100,23724121
2018-01-18 13:20:00,SPY,2018-01-18,279.4800,279.8250,279.1600,279.6200,4718455
2018-01-18 15:00:00,SPY,2018-01-18,279.6300,279.6600,278.7600,278.9300,13511930
2018-01-18 16:40:00,SPY,2018-01-18,278.9300,279.3600,278.5800,279.2000,8668574
2018-01-18 18:20:00,SPY,2018-01-18,279.1900,279.9600,279.0700,279.6650,15489102
2018-01-18 20:00:00,SPY,2018-01-18,279.6700,279.7200,278.8600,279.1800,19475932
2018-01-19 13:20:00,SPY,2018-01-19,279.8000,279.9900,279.6500,279.7600,7125686
2018-01-19 15:00:00,SPY,2018-01-19,279.7501,279.9600,279.1400,279.5300,11286005
2018-01-19 16:40:00,SPY,2018-01-19,279.5200,279.8000,279.3200,279.6600,6456721
2018-01-19 18:20:00,SPY,2018-01-19,279.6600,280.1500,279.4500,279.9600,10030332
2018-01-19 20:00:00,SPY,2018-01-19,279.9600,280.4100,279.8400,280.3900,22134207
2018-01-22 13:20:00,SPY,2018-01-22,280.1700,280.7600,280.1100,280.6650,3318932
2018-01-22 15:00:00,SPY,2018-01-22,280.6600,281.4300,280.5900,281.2000,12755306
2018-01-22 16:40:00,SPY,2018-01-22,281.1900,281.9600,281.0211,281.8300,8784088
2018-01-22 18:20:00,SPY,2018-01-22,281.8300,281.8900,281.4500,281.7100,6083139
2018-01-22 20:00:00,SPY,2018-01-22,281.7100,282.6900,281.6800,282.6700,27841706
2018-01-23 13:20:00,SPY,2018-01-23,282.7400,283.3100,282.3700,282.6500,8194270
2018-01-23 15:00:00,SPY,2018-01-23,282.6500,283.6200,282.4700,283.2289,12117111
2018-01-23 16:40:00,SPY,2018-01-23,283.2300,283.3325,282.8400,283.0600,7985114
2018-01-23 18:20:00,SPY,2018-01-23,283.0600,283.5100,282.8800,283.3800,10036366
2018-01-23 20:00:00,SPY,2018-01-23,283.3800,283.5400,283.0200,283.2400,17201065
2018-01-24 13:20:00,SPY,2018-01-24,284.0200,284.3400,283.7500,284.2800,6171946
2018-01-24 15:00:00,SPY,2018-01-24,284.2800,284.7000,282.3800,282.8700,22765020
2018-01-24 16:40:00,SPY,2018-01-24,282.8700,283.4300,281.8400,281.9900,15869299
2018-01-24 18:20:00,SPY,2018-01-24,281.9800,283.7600,281.8600,283.4600,16174006
2018-01-24 20:00:00,SPY,2018-01-24,283.4800,283.7700,283.0600,283.1200,17699686

In [25]:
i="AAPL"
price=pd.DataFrame()
temp = robinhood.get_historical(i,interval="10minute",span = "week")
temp = temp.drop(["session","interpolated"],axis=1)

for j in temp.columns[1:]:
    temp[j] = temp[j].astype(float)
temp["Ticker"] = np.repeat(i,len(temp))
price = price.append(temp)

In [20]:
def get_ondemand_data_test(sym, interval = 1,freq = 'minutes' ,start_date=(datetime.now()-timedelta(days=10))\
                    ,end_date=datetime.now()):



    api_key = 'b59b144a62e058b6c4e265c049dc679f'
    start_date=start_date.strftime("%Y%m%d%H%M%S")
    end_date=end_date.strftime("%Y%m%d%H%M%S")
    # This is the required format for datetimes to access the API

    api_url = 'http://marketdata.websol.barchart.com/getHistory.csv?' + \
                            'key={}&symbol={}&type={}&startDate={}&endDate={}&interval={}'\
                             .format(api_key, sym, freq, start_date,end_date,interval)

    csvfile = pd.read_csv(api_url)
    #csvfile.set_index('timestamp', inplace=True)

    return csvfile

In [36]:
get_ondemand_data()

TypeError: get_ondemand_data() takes at least 1 argument (0 given)